CREATE TABLE feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    mensagem TEXT NOT NULL,
    data_envio TIMESTAMP NOT NULL,
    resolvido BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_feedbacks_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);